timezone: Asia/Jakarta
excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://yusuphm.github.io
title: Yusuphm
tagline: A log of everyday life
description: My awesome new site
paginate: 5
